import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Oswald,
  Barlow_Condensed,
  Quicksand,
} from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";
import CustomCursor from "./custom_cursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-oswald",
});

const barlowCondensed = Barlow_Condensed({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={oswald.className}>
      <body
        // suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${barlowCondensed.variable} ${quicksand.variable} antialiased `}
      >
        <CustomCursor />
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
